development:
  adapter: postgresql
  encoding: unicode
  database: chalkhouse_db_development
  pool: 5
  username: markpaul
  password: markpaul
  host: localhost
  port: 5434

test:
  adapter: postgresql
  encoding: unicode
  database: chalkhouse_db_test
  pool: 5
  username: markpaul
  password: markpaul
  host: localhost
  port: 5434

production:
  adapter: postgresql
  encoding: unicode
  database: chalkhouse_db_production
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: markpaul
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5434
  timeout: 5000
